/**
 * Server-side access to the local Quran dataset.
 *
 * This module reads `data/quran.json` (generated by `scripts/convert-quran.ts`)
 * from disk and must stay server-only — the `node:fs` import means importing it
 * from a client component fails the build, which is the guarantee we want.
 * Never pass the parsed dataset to a client component; pass summaries instead.
 */

import { readFileSync } from "node:fs";
import { join } from "node:path";
import { cache } from "react";
import type {
  Quran,
  QuranPage,
  QuranPageAyah,
  QuranPageStart,
  SurahSummary,
} from "@/types/quran";

const DATA_FILE = join(process.cwd(), "data", "quran.json");
const PAGES_FILE = join(process.cwd(), "data", "quran-pages.json");

/** Parses the dataset once per request. */
const loadQuran = cache(
  (): Quran => JSON.parse(readFileSync(DATA_FILE, "utf8")) as Quran,
);

const loadQuranPages = cache(
  (): QuranPageStart[] =>
    JSON.parse(readFileSync(PAGES_FILE, "utf8")) as QuranPageStart[],
);

/**
 * All ayahs in Mushaf order, carrying Surah context. Cached so page slices do
 * not rebuild the 6,236-ayah list on every lookup.
 */
const getOrderedAyahs = cache((): QuranPageAyah[] =>
  loadQuran().surahs.flatMap((surah) =>
    surah.ayahs.map((ayah) => {
      const item: QuranPageAyah = {
        surahNumber: surah.number,
        surahName: surah.name,
        ayahNumber: ayah.number,
        text: ayah.text,
      };

      if (ayah.bismillah !== undefined) {
        item.bismillah = ayah.bismillah;
      }

      return item;
    }),
  ),
);

function findAyahIndex(
  ayahs: QuranPageAyah[],
  sura: number,
  aya: number,
): number {
  return ayahs.findIndex(
    (ayah) => ayah.surahNumber === sura && ayah.ayahNumber === aya,
  );
}

/** Lightweight list for the surah index; safe to serialize to the client. */
export const getSurahSummaries = cache((): SurahSummary[] =>
  loadQuran().surahs.map((surah) => {
    const firstPage = getFirstPageOfSurah(surah.number);

    if (firstPage === undefined) {
      throw new Error(`No Mushaf page contains ${surah.number}:1`);
    }

    return {
      number: surah.number,
      name: surah.name,
      ayahCount: surah.ayahs.length,
      firstPage,
    };
  }),
);

export const getSurahByNumber = cache((surahNumber: number) => {
  return loadQuran().surahs.find((surah) => surah.number === surahNumber);
});

export const getMushafPageCount = cache((): number => loadQuranPages().length);

/**
 * Ayahs belonging to one Madinah Mushaf page.
 *
 * Boundaries come only from `quran-pages.json`: a page starts at its mapped
 * (sura, aya) and ends immediately before the next page's start. Page 604 has
 * no successor, so it continues through the final ayah of the Quran.
 */
export const getQuranPage = cache((pageNumber: number): QuranPage | undefined => {
  if (!Number.isInteger(pageNumber)) {
    return undefined;
  }

  const pages = loadQuranPages();
  const currentPage = pages.find((page) => page.page === pageNumber);

  if (!currentPage) {
    return undefined;
  }

  const nextPage = pages.find((page) => page.page === pageNumber + 1);
  const ayahs = getOrderedAyahs();
  const startIndex = findAyahIndex(ayahs, currentPage.sura, currentPage.aya);

  if (startIndex === -1) {
    return undefined;
  }

  let endIndex = ayahs.length;

  if (nextPage) {
    const nextIndex = findAyahIndex(ayahs, nextPage.sura, nextPage.aya);
    if (nextIndex === -1) {
      return undefined;
    }
    endIndex = nextIndex;
  }

  return {
    pageNumber,
    ayahs: ayahs.slice(startIndex, endIndex),
  };
});
/**
 * Mushaf page that contains ayah 1 of a Surah.
 *
 * Page starts are not a reliable Surah index — a Surah can begin in the
 * middle of a page whose boundary is still the previous Surah. This walks the
 * same `getQuranPage()` slices the reader uses and returns the page that
 * actually includes `{surahNumber}:1`.
 */
export const getFirstPageOfSurah = cache(
  (surahNumber: number): number | undefined => {
    if (!Number.isInteger(surahNumber) || !getSurahByNumber(surahNumber)) {
      return undefined;
    }

    const totalPages = getMushafPageCount();

    for (let pageNumber = 1; pageNumber <= totalPages; pageNumber += 1) {
      const page = getQuranPage(pageNumber);
      const containsFirstAyah = page?.ayahs.some(
        (ayah) =>
          ayah.surahNumber === surahNumber && ayah.ayahNumber === 1,
      );

      if (containsFirstAyah) {
        return pageNumber;
      }
    }

    return undefined;
  },
);

/** Exact ayah from the local dataset — never invents or rewrites text. */
export const getAyah = cache(
  (
    surahNumber: number,
    ayahNumber: number,
  ): QuranPageAyah | undefined => {
    if (!Number.isInteger(surahNumber) || !Number.isInteger(ayahNumber)) {
      return undefined;
    }

    const surah = getSurahByNumber(surahNumber);
    const ayah = surah?.ayahs.find((item) => item.number === ayahNumber);

    if (!surah || !ayah) {
      return undefined;
    }

    const item: QuranPageAyah = {
      surahNumber: surah.number,
      surahName: surah.name,
      ayahNumber: ayah.number,
      text: ayah.text,
    };

    if (ayah.bismillah !== undefined) {
      item.bismillah = ayah.bismillah;
    }

    return item;
  },
);

/** Next or previous ayah in Mushaf order, using local quran.json only. */
export const getAdjacentAyah = cache(
  (
    surahNumber: number,
    ayahNumber: number,
    direction: "next" | "previous",
  ): QuranPageAyah | undefined => {
    const ayahs = getOrderedAyahs();
    const index = findAyahIndex(ayahs, surahNumber, ayahNumber);
    if (index === -1) {
      return undefined;
    }

    const adjacentIndex = direction === "next" ? index + 1 : index - 1;
    if (adjacentIndex < 0 || adjacentIndex >= ayahs.length) {
      return undefined;
    }

    return ayahs[adjacentIndex];
  },
);

/**
 * Inclusive ayah range within one Surah, in Quran order.
 * Returns undefined if the range is invalid or crosses Surah bounds.
 */
export const getAyahRange = cache(
  (
    surahNumber: number,
    startAyahNumber: number,
    endAyahNumber: number,
  ): QuranPageAyah[] | undefined => {
    if (
      !Number.isInteger(surahNumber) ||
      !Number.isInteger(startAyahNumber) ||
      !Number.isInteger(endAyahNumber)
    ) {
      return undefined;
    }

    const start = Math.min(startAyahNumber, endAyahNumber);
    const end = Math.max(startAyahNumber, endAyahNumber);
    const surah = getSurahByNumber(surahNumber);

    if (!surah || start < 1 || end > surah.ayahs.length) {
      return undefined;
    }

    const ayahs: QuranPageAyah[] = [];
    for (let n = start; n <= end; n += 1) {
      const ayah = getAyah(surahNumber, n);
      if (!ayah) {
        return undefined;
      }
      ayahs.push(ayah);
    }

    return ayahs;
  },
);

const getPageStartIndexes = cache(() => {
  const ayahs = getOrderedAyahs();
  return loadQuranPages().map((page) => ({
    page: page.page,
    startIndex: findAyahIndex(ayahs, page.sura, page.aya),
  }));
});

/** Mushaf page that contains a given (surah, ayah). */
export const getPageForAyah = cache(
  (surahNumber: number, ayahNumber: number): number | undefined => {
    const ayahs = getOrderedAyahs();
    const index = findAyahIndex(ayahs, surahNumber, ayahNumber);

    if (index === -1) {
      return undefined;
    }

    let pageNumber: number | undefined;

    for (const start of getPageStartIndexes()) {
      if (start.startIndex === -1) {
        continue;
      }
      if (start.startIndex <= index) {
        pageNumber = start.page;
      } else {
        break;
      }
    }

    return pageNumber;
  },
);