/**
 * Server-side access to the local Quran dataset.
 *
 * This module reads `data/quran.json` (generated by `scripts/convert-quran.ts`),
 * `data/quran-pages.json`, `data/quran-juz.json`, and `data/quran-rub.json`
 * from disk and must stay server-only — the `node:fs` import means importing
 * it from a client component fails the build, which is the guarantee we want.
 * Never pass the parsed dataset to a client component; pass summaries instead.
 */

import { readFileSync } from "node:fs";
import { join } from "node:path";
import { cache } from "react";
import type {
  JuzBoundary,
  JuzSummary,
  Quran,
  QuranPage,
  QuranPageAyah,
  QuranPageStart,
  RubAyahMarker,
  RubBoundary,
  RubQuarterInHizb,
  RubQuarterSource,
  SurahSummary,
} from "@/types/quran";

const DATA_FILE = join(process.cwd(), "data", "quran.json");
const PAGES_FILE = join(process.cwd(), "data", "quran-pages.json");
const JUZ_FILE = join(process.cwd(), "data", "quran-juz.json");
const RUB_FILE = join(process.cwd(), "data", "quran-rub.json");
const JUZ_COUNT = 30;
/** Tanzil numbers quarters globally. Four quarters make one Hizb. */
const QUARTERS_PER_HIZB = 4;
/** Two Hizb make one Juz, so eight quarters align with each local Juz start. */
const QUARTERS_PER_JUZ = 8;

type JuzMetadataFile = {
  juzs: JuzBoundary[];
};

type RubMetadataFile = {
  quarters: RubQuarterSource[];
};

/** Parsed once per server process. File contents are not rewritten. */
let quranCache: Quran | undefined;
let pageCache: QuranPageStart[] | undefined;
let juzCache: JuzBoundary[] | undefined;
let rubCache: RubQuarterSource[] | undefined;
let orderedAyahCache: QuranPageAyah[] | undefined;

const loadQuran = cache((): Quran => {
  quranCache ??= JSON.parse(readFileSync(DATA_FILE, "utf8")) as Quran;
  return quranCache;
});

const loadQuranPages = cache((): QuranPageStart[] => {
  pageCache ??= JSON.parse(readFileSync(PAGES_FILE, "utf8")) as QuranPageStart[];
  return pageCache;
});

const loadJuzBoundaries = cache((): JuzBoundary[] => {
  if (!juzCache) {
    const file = JSON.parse(readFileSync(JUZ_FILE, "utf8")) as JuzMetadataFile;
    juzCache = file.juzs;
  }
  return juzCache;
});

const loadRubQuarters = cache((): RubQuarterSource[] => {
  if (!rubCache) {
    const file = JSON.parse(readFileSync(RUB_FILE, "utf8")) as RubMetadataFile;
    rubCache = file.quarters;
  }
  return rubCache;
});

/**
 * All ayahs in Mushaf order, carrying Surah context. Built once so page slices
 * do not rebuild the 6,236-ayah list on every lookup.
 */
const getOrderedAyahs = cache((): QuranPageAyah[] => {
  orderedAyahCache ??= loadQuran().surahs.flatMap((surah) =>
    surah.ayahs.map((ayah) => {
      const item: QuranPageAyah = {
        surahNumber: surah.number,
        surahName: surah.name,
        ayahNumber: ayah.number,
        text: ayah.text,
      };

      if (ayah.bismillah !== undefined) {
        item.bismillah = ayah.bismillah;
      }

      return item;
    }),
  );
  return orderedAyahCache;
});

/** Surah numbers from the local dataset, without scanning Mushaf pages. */
export function listSurahNumbers(): number[] {
  return loadQuran().surahs.map((surah) => surah.number);
}

function findAyahIndex(
  ayahs: QuranPageAyah[],
  sura: number,
  aya: number,
): number {
  return ayahs.findIndex(
    (ayah) => ayah.surahNumber === sura && ayah.ayahNumber === aya,
  );
}

/** Lightweight list for the surah index; safe to serialize to the client. */
export const getSurahSummaries = cache((): SurahSummary[] =>
  loadQuran().surahs.map((surah) => {
    const firstPage = getFirstPageOfSurah(surah.number);

    if (firstPage === undefined) {
      throw new Error(`No Mushaf page contains ${surah.number}:1`);
    }

    return {
      number: surah.number,
      name: surah.name,
      ayahCount: surah.ayahs.length,
      firstPage,
    };
  }),
);

export const getSurahByNumber = cache((surahNumber: number) => {
  return loadQuran().surahs.find((surah) => surah.number === surahNumber);
});

export const getMushafPageCount = cache((): number => loadQuranPages().length);

/**
 * Ayahs belonging to one Madinah Mushaf page.
 *
 * Boundaries come only from `quran-pages.json`: a page starts at its mapped
 * (sura, aya) and ends immediately before the next page's start. Page 604 has
 * no successor, so it continues through the final ayah of the Quran.
 */
export const getQuranPage = cache((pageNumber: number): QuranPage | undefined => {
  if (!Number.isInteger(pageNumber)) {
    return undefined;
  }

  const pages = loadQuranPages();
  const currentPage = pages.find((page) => page.page === pageNumber);

  if (!currentPage) {
    return undefined;
  }

  const nextPage = pages.find((page) => page.page === pageNumber + 1);
  const ayahs = getOrderedAyahs();
  const startIndex = findAyahIndex(ayahs, currentPage.sura, currentPage.aya);

  if (startIndex === -1) {
    return undefined;
  }

  let endIndex = ayahs.length;

  if (nextPage) {
    const nextIndex = findAyahIndex(ayahs, nextPage.sura, nextPage.aya);
    if (nextIndex === -1) {
      return undefined;
    }
    endIndex = nextIndex;
  }

  return {
    pageNumber,
    ayahs: ayahs.slice(startIndex, endIndex),
  };
});
/**
 * Mushaf page that contains ayah 1 of a Surah.
 *
 * Page starts are not a reliable Surah index — a Surah can begin in the
 * middle of a page whose boundary is still the previous Surah. This walks the
 * same `getQuranPage()` slices the reader uses and returns the page that
 * actually includes `{surahNumber}:1`.
 */
export const getFirstPageOfSurah = cache(
  (surahNumber: number): number | undefined => {
    if (!Number.isInteger(surahNumber) || !getSurahByNumber(surahNumber)) {
      return undefined;
    }

    const totalPages = getMushafPageCount();

    for (let pageNumber = 1; pageNumber <= totalPages; pageNumber += 1) {
      const page = getQuranPage(pageNumber);
      const containsFirstAyah = page?.ayahs.some(
        (ayah) =>
          ayah.surahNumber === surahNumber && ayah.ayahNumber === 1,
      );

      if (containsFirstAyah) {
        return pageNumber;
      }
    }

    return undefined;
  },
);

/** Exact ayah from the local dataset — never invents or rewrites text. */
export const getAyah = cache(
  (
    surahNumber: number,
    ayahNumber: number,
  ): QuranPageAyah | undefined => {
    if (!Number.isInteger(surahNumber) || !Number.isInteger(ayahNumber)) {
      return undefined;
    }

    const surah = getSurahByNumber(surahNumber);
    const ayah = surah?.ayahs.find((item) => item.number === ayahNumber);

    if (!surah || !ayah) {
      return undefined;
    }

    const item: QuranPageAyah = {
      surahNumber: surah.number,
      surahName: surah.name,
      ayahNumber: ayah.number,
      text: ayah.text,
    };

    if (ayah.bismillah !== undefined) {
      item.bismillah = ayah.bismillah;
    }

    return item;
  },
);

/** Next or previous ayah in Mushaf order, using local quran.json only. */
export const getAdjacentAyah = cache(
  (
    surahNumber: number,
    ayahNumber: number,
    direction: "next" | "previous",
  ): QuranPageAyah | undefined => {
    const ayahs = getOrderedAyahs();
    const index = findAyahIndex(ayahs, surahNumber, ayahNumber);
    if (index === -1) {
      return undefined;
    }

    const adjacentIndex = direction === "next" ? index + 1 : index - 1;
    if (adjacentIndex < 0 || adjacentIndex >= ayahs.length) {
      return undefined;
    }

    return ayahs[adjacentIndex];
  },
);

/**
 * Inclusive ayah range within one Surah, in Quran order.
 * Returns undefined if the range is invalid or crosses Surah bounds.
 */
export const getAyahRange = cache(
  (
    surahNumber: number,
    startAyahNumber: number,
    endAyahNumber: number,
  ): QuranPageAyah[] | undefined => {
    if (
      !Number.isInteger(surahNumber) ||
      !Number.isInteger(startAyahNumber) ||
      !Number.isInteger(endAyahNumber)
    ) {
      return undefined;
    }

    const start = Math.min(startAyahNumber, endAyahNumber);
    const end = Math.max(startAyahNumber, endAyahNumber);
    const surah = getSurahByNumber(surahNumber);

    if (!surah || start < 1 || end > surah.ayahs.length) {
      return undefined;
    }

    const ayahs: QuranPageAyah[] = [];
    for (let n = start; n <= end; n += 1) {
      const ayah = getAyah(surahNumber, n);
      if (!ayah) {
        return undefined;
      }
      ayahs.push(ayah);
    }

    return ayahs;
  },
);

const getPageStartIndexes = cache(() => {
  const ayahs = getOrderedAyahs();
  return loadQuranPages().map((page) => ({
    page: page.page,
    startIndex: findAyahIndex(ayahs, page.sura, page.aya),
  }));
});

/** Mushaf page that contains a given (surah, ayah). */
export const getPageForAyah = cache(
  (surahNumber: number, ayahNumber: number): number | undefined => {
    const ayahs = getOrderedAyahs();
    const index = findAyahIndex(ayahs, surahNumber, ayahNumber);

    if (index === -1) {
      return undefined;
    }

    let pageNumber: number | undefined;

    for (const start of getPageStartIndexes()) {
      if (start.startIndex === -1) {
        continue;
      }
      if (start.startIndex <= index) {
        pageNumber = start.page;
      } else {
        break;
      }
    }

    return pageNumber;
  },
);

/**
 * The 30 Juz, with each start ayah checked against the local Quran text and
 * each Mushaf page resolved from `quran-pages.json`.
 *
 * Boundaries come only from `data/quran-juz.json` (Tanzil quran-data.xml).
 */
export const getJuzSummaries = cache((): JuzSummary[] => {
  const boundaries = loadJuzBoundaries();

  if (boundaries.length !== JUZ_COUNT) {
    throw new Error(`Expected ${JUZ_COUNT} juz, found ${boundaries.length}`);
  }

  const ayahs = getOrderedAyahs();
  const pageCount = getMushafPageCount();
  const seen = new Set<number>();
  const summaries: JuzSummary[] = [];
  let previousIndex = -1;

  for (const boundary of boundaries) {
    const { number, startSurah, startAyah } = boundary;

    if (!Number.isInteger(number) || number < 1 || number > JUZ_COUNT) {
      throw new Error(`Invalid juz number ${String(number)}`);
    }

    if (seen.has(number)) {
      throw new Error(`Duplicate juz number ${number}`);
    }

    seen.add(number);

    const index = findAyahIndex(ayahs, startSurah, startAyah);

    if (index === -1) {
      throw new Error(
        `Juz ${number} does not start at a local ayah (${startSurah}:${startAyah})`,
      );
    }

    if (index <= previousIndex) {
      throw new Error(`Juz ${number} is not after the previous juz in Mushaf order`);
    }

    previousIndex = index;

    const startPage = getPageForAyah(startSurah, startAyah);

    if (
      startPage === undefined ||
      startPage < 1 ||
      startPage > pageCount
    ) {
      throw new Error(
        `Juz ${number} does not resolve to a Mushaf page (${startSurah}:${startAyah})`,
      );
    }

    summaries.push({ number, startSurah, startAyah, startPage });
  }

  for (let number = 1; number <= JUZ_COUNT; number += 1) {
    if (!seen.has(number)) {
      throw new Error(`Missing juz ${number}`);
    }
  }

  if (summaries.some((juz, index) => juz.number !== index + 1)) {
    throw new Error("Juz metadata is not ordered from 1 to 30");
  }

  return summaries;
});

export const getJuzByNumber = cache(
  (juzNumber: number): JuzSummary | undefined => {
    if (!Number.isInteger(juzNumber)) {
      return undefined;
    }

    return getJuzSummaries().find((juz) => juz.number === juzNumber);
  },
);

function quarterInHizb(index: number): RubQuarterInHizb {
  const value = ((index - 1) % QUARTERS_PER_HIZB) + 1;
  if (value === 1 || value === 2 || value === 3 || value === 4) {
    return value;
  }
  throw new Error(`Invalid quarter position for rub index ${index}`);
}

type IndexedRub = RubBoundary & { ayahIndex: number };

/**
 * Rubʿ boundaries from `data/quran-rub.json`.
 *
 * Tanzil stores them as `<hizbs alias="groups"><quarter index sura aya/></hizbs>`.
 * `index` is global. Hizb, quarter-in-hizb, and Juz are derived and checked
 * against `quran-juz.json`: quarter `(juz - 1) * 8 + 1` must be that Juz start.
 */
const getIndexedRubs = cache((): IndexedRub[] => {
  const quarters = loadRubQuarters();

  if (quarters.length === 0 || quarters.length % QUARTERS_PER_JUZ !== 0) {
    throw new Error(
      `Rub quarter count ${quarters.length} is not a multiple of ${QUARTERS_PER_JUZ}`,
    );
  }

  const ayahs = getOrderedAyahs();
  const ayahIndexByKey = new Map<string, number>();
  ayahs.forEach((ayah, index) => {
    ayahIndexByKey.set(`${ayah.surahNumber}:${ayah.ayahNumber}`, index);
  });

  const pageCount = getMushafPageCount();
  const seenIndexes = new Set<number>();
  const seenAyahs = new Set<string>();
  const resolved: IndexedRub[] = [];
  let previousAyahIndex = -1;

  for (const quarter of quarters) {
    const { index, startSurah, startAyah } = quarter;

    if (!Number.isInteger(index) || index < 1) {
      throw new Error(`Invalid rub index ${String(index)}`);
    }
    if (seenIndexes.has(index)) {
      throw new Error(`Duplicate rub index ${index}`);
    }
    seenIndexes.add(index);

    const ayahKey = `${startSurah}:${startAyah}`;
    if (seenAyahs.has(ayahKey)) {
      throw new Error(`Duplicate rub boundary at ${ayahKey}`);
    }
    seenAyahs.add(ayahKey);

    const ayahIndex = ayahIndexByKey.get(ayahKey);
    if (ayahIndex === undefined) {
      throw new Error(
        `Rub ${index} does not start at a local ayah (${ayahKey})`,
      );
    }
    if (ayahIndex <= previousAyahIndex) {
      throw new Error(`Rub ${index} is not after the previous rub in Mushaf order`);
    }
    previousAyahIndex = ayahIndex;

    const startPage = getPageForAyah(startSurah, startAyah);
    if (
      startPage === undefined ||
      startPage < 1 ||
      startPage > pageCount
    ) {
      throw new Error(`Rub ${index} does not resolve to a Mushaf page (${ayahKey})`);
    }

    resolved.push({
      rubNumber: index,
      hizbNumber: Math.ceil(index / QUARTERS_PER_HIZB),
      quarterInHizb: quarterInHizb(index),
      juzNumber: Math.ceil(index / QUARTERS_PER_JUZ),
      startSurah,
      startAyah,
      startPage,
      ayahIndex,
    });
  }

  if (resolved.some((rub, position) => rub.rubNumber !== position + 1)) {
    throw new Error("Rub metadata is not ordered from 1");
  }

  const juzs = getJuzSummaries();
  if (resolved.length / QUARTERS_PER_JUZ !== juzs.length) {
    throw new Error(
      `Rub quarters (${resolved.length}) do not line up with ${juzs.length} juz`,
    );
  }

  for (const juz of juzs) {
    const rub = resolved[(juz.number - 1) * QUARTERS_PER_JUZ];
    if (
      !rub ||
      rub.startSurah !== juz.startSurah ||
      rub.startAyah !== juz.startAyah ||
      rub.juzNumber !== juz.number
    ) {
      throw new Error(
        `Rub alignment does not match Juz ${juz.number} (${juz.startSurah}:${juz.startAyah})`,
      );
    }
  }

  return resolved;
});

/** All Rubʿ boundaries, in Tanzil index order, with resolved Mushaf pages. */
export const getRubBoundaries = cache((): RubBoundary[] =>
  getIndexedRubs().map((rub) => ({
    rubNumber: rub.rubNumber,
    hizbNumber: rub.hizbNumber,
    quarterInHizb: rub.quarterInHizb,
    juzNumber: rub.juzNumber,
    startSurah: rub.startSurah,
    startAyah: rub.startAyah,
    startPage: rub.startPage,
  })),
);

const getRubStartMap = cache(() => {
  const map = new Map<string, RubBoundary>();
  for (const rub of getRubBoundaries()) {
    map.set(`${rub.startSurah}:${rub.startAyah}`, rub);
  }
  return map;
});

/** The Rubʿ that begins at this exact ayah, if any. */
export const getRubStartAtAyah = cache(
  (surahNumber: number, ayahNumber: number): RubBoundary | undefined => {
    if (!Number.isInteger(surahNumber) || !Number.isInteger(ayahNumber)) {
      return undefined;
    }
    return getRubStartMap().get(`${surahNumber}:${ayahNumber}`);
  },
);

/** The Rubʿ that contains this ayah (the latest boundary at or before it). */
export const getRubForAyah = cache(
  (surahNumber: number, ayahNumber: number): RubBoundary | undefined => {
    if (!Number.isInteger(surahNumber) || !Number.isInteger(ayahNumber)) {
      return undefined;
    }

    const ayahs = getOrderedAyahs();
    const index = findAyahIndex(ayahs, surahNumber, ayahNumber);
    if (index === -1) {
      return undefined;
    }

    let current: IndexedRub | undefined;
    for (const rub of getIndexedRubs()) {
      if (rub.ayahIndex <= index) {
        current = rub;
      } else {
        break;
      }
    }

    if (!current) {
      return undefined;
    }

    return {
      rubNumber: current.rubNumber,
      hizbNumber: current.hizbNumber,
      quarterInHizb: current.quarterInHizb,
      juzNumber: current.juzNumber,
      startSurah: current.startSurah,
      startAyah: current.startAyah,
      startPage: current.startPage,
    };
  },
);

/** Rubʿ starts that fall on the given ayahs. Matching is exact Surah + Ayah. */
export function getRubMarkersForAyahs(
  ayahs: readonly { surahNumber: number; ayahNumber: number }[],
): RubAyahMarker[] {
  const markers: RubAyahMarker[] = [];
  for (const ayah of ayahs) {
    const rub = getRubStartAtAyah(ayah.surahNumber, ayah.ayahNumber);
    if (!rub) continue;
    markers.push({
      surahNumber: rub.startSurah,
      ayahNumber: rub.startAyah,
      hizbNumber: rub.hizbNumber,
      quarterInHizb: rub.quarterInHizb,
    });
  }
  return markers;
}